"""
run_all.py — Master analysis runner

Executes all four analysis scripts in order, then combines
their JSON outputs into a single results/all_data.js file
that the HTML report loads via <script src="results/all_data.js">.

Usage:
    python scripts/run_all.py
"""
import json
import importlib.util
import sys
from pathlib import Path

SCRIPTS_DIR = Path(__file__).parent
RESULTS_DIR = SCRIPTS_DIR.parent / "results"


def run_script(name):
    path = SCRIPTS_DIR / name
    spec = importlib.util.spec_from_file_location(name.stem, path)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    mod.main()


def build_js_bundle():
    """Merge all result JSONs into a single JS variable for the HTML report."""
    keys = {
        "phase1": "phase1_overview.json",
        "q1":     "phase2_investors.json",
        "q2":     "phase2_flips.json",
        "q3":     "phase2_cash.json",
    }
    bundle = {}
    for key, filename in keys.items():
        p = RESULTS_DIR / filename
        with open(p) as f:
            bundle[key] = json.load(f)

    js = "// AUTO-GENERATED by run_all.py — do not edit by hand\n"
    js += "// Re-generate with: python scripts/run_all.py\n"
    js += "const REPORT_DATA = " + json.dumps(bundle, indent=2) + ";\n"

    out_path = RESULTS_DIR / "all_data.js"
    with open(out_path, "w") as f:
        f.write(js)
    print(f"\nBundled → {out_path}  ({out_path.stat().st_size // 1024} KB)")


def main():
    RESULTS_DIR.mkdir(exist_ok=True)
    scripts = [
        "phase1_overview.py",
        "phase2_investors.py",
        "phase2_flips.py",
        "phase2_cash.py",
        "generate_figures.py",
    ]
    for s in scripts:
        print(f"\n{'─'*50}")
        print(f"Running {s} ...")
        print('─'*50)
        run_script(Path(s))

    print(f"\n{'─'*50}")
    print("Building JS bundle ...")
    build_js_bundle()
    print("\nAll done. Open report.html in a browser.")
    print("(figures.js is written by generate_figures.py above)")


if __name__ == "__main__":
    main()
